DROP DATABASE IF EXISTS bamazonDB;

CREATE DATABASE bamazonDB;

USE bamazonDB;

CREATE TABLE products (
id INT AUTO_INCREMENT NOT NULL, 
product_name VARCHAR(255) NOT NULL, 
department_name VARCHAR(255) NOT NULL, 
price DECIMAL(10,2) NOT NULL, 
stock_quantity INT(100) NOT NULL
PRIMARY KEY (id)
);

